require: rubocop-performance

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5.3
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/FileName:
  Enabled: false
